// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPFJFgtqHsOUXq_JNopUXER0vtX6WJhx0',
    appId: '1:769679895411:web:5ca23598a5c4f7afb8f306',
    messagingSenderId: '769679895411',
    projectId: 'brl-task-2',
    authDomain: 'brl-task-2.firebaseapp.com',
    storageBucket: 'brl-task-2.firebasestorage.app',
    measurementId: 'G-6BTDHX058N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8y-8uR-NRym3HcNBXBgOiYaQEkp-YR2E',
    appId: '1:769679895411:android:8b712d9035f8ee79b8f306',
    messagingSenderId: '769679895411',
    projectId: 'brl-task-2',
    storageBucket: 'brl-task-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLh9ujIFKLJ0h2Qj8lX_Dw4N9kz9KwYV8',
    appId: '1:769679895411:ios:d7b97da382b20f27b8f306',
    messagingSenderId: '769679895411',
    projectId: 'brl-task-2',
    storageBucket: 'brl-task-2.firebasestorage.app',
    iosBundleId: 'com.example.brlTask2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLh9ujIFKLJ0h2Qj8lX_Dw4N9kz9KwYV8',
    appId: '1:769679895411:ios:d7b97da382b20f27b8f306',
    messagingSenderId: '769679895411',
    projectId: 'brl-task-2',
    storageBucket: 'brl-task-2.firebasestorage.app',
    iosBundleId: 'com.example.brlTask2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPFJFgtqHsOUXq_JNopUXER0vtX6WJhx0',
    appId: '1:769679895411:web:294730d9be48d672b8f306',
    messagingSenderId: '769679895411',
    projectId: 'brl-task-2',
    authDomain: 'brl-task-2.firebaseapp.com',
    storageBucket: 'brl-task-2.firebasestorage.app',
    measurementId: 'G-G2E8MJ8QPJ',
  );
}
